### ISSUE TITLE
Issues abour eq(1)

### ISSUE THREAD

**Issue by Theheavens** [pnnl/SLiCE#1]
I am wondering whether the eq(1) equals message passing method? Like GCN, it's AXW. But it's WXA in paper. The dimension of W is d*d, X is |Vc|*d, A is |Vc| *|Vc|. The matirx multiplication WXA is ok? Or it should be AXW?

**Comment by wangpinggl** [comment]
The dimension of X is d*|Vc| here. See section 3.3 in page 4.

**Comment by Theheavens** [comment]
Thanks a lot!
