### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by AnoushkaVyas** [pnnl/SLiCE#4]
torch_scatter, torch_sparse, torch_spline_conv, torch_cluster are not getting installed even after explicitly running their wheel files. Kindly look into this and suggest something.

**Comment by colbyham** [comment]
What OS are you running on? Did you make sure you are using Python 3.6 w/ CUDA 9.2 (GPU required)? To install wheel files on Linux, you can use 'pip install wheels/linux/torch_cluster-1.5.4-cp36-cp36m-linux_x86_64.whl', for example.

**Comment by AnoushkaVyas** [comment]
using linux virtual machine. I have tried those installation commands but when I am running python main.py, it is giving module import error for these four.

**Comment by colbyham** [comment]
I created clearer instructions in an install script, [install.sh](https://github.com/pnnl/SLiCE/blob/master/install.sh), and added it to the repo. Could you try to run it from your command line and screenshot what errors you are getting?
